#!/bin/sh

# Credit to youtube.com/@bugswriter_

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

if [ -z "$1" ]; then
    url=""
else
    url="$1"
fi

prefix="setsid -f"
quiet="--quiet"
redirect="/dev/null"
suffix="&"
case $(tty) in /dev/tty[0-9]*)
    prefix=""; quiet=""; redirect="1"; suffix="" ;;
esac

case "$url" in
    *nkv|!webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtub.com/shorts*|*youtube.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*|*odysee.com*)
        $prefix mpv --force-window=yes --script-opts=ytdl_hook-ytdl_path=yt-dlp,ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="*.webm$|*.ts$|*.mp3$|*.m3u8$|*.m3u$|*.mkv$|*.mp4$|*.VOB$" --fullscreen --ytdl-format='w[height=1080][protocol=m3u8_native][language=en]/wa+wv[height=1080][protocol=m3u8_native][language=en]/w[height<=1080][height>=720][language=en]/wa+wv[height<=1080][height>=720][protocol=m3u8_native][language=en]/22/b/ba+bv' $quiet "$url" >&$redirect 2>&1 ;;
    *png|*jpg|*jpeg|*gif)
        curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && sxiv -a "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" >&$redirect 2>&1 $suffix ;;
    *pdf|*cbz|*cbr)
        curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && evince "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" >&$redirect 2>&1 $suffix ;;
    *np3|*flac|*opus|*mp3?source*)
        $prefix mpv --force-window=yes --script-opts=ytdl_hook-ytdl_path=yt-dlp,ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="*.webm$|*.ts$|*.mp3$|*.m3u8$|*.m3u$|*.mkv$|*.mp4$|*.VOB$" --fullscreen --ytdl-format='w[height=1080][protocol=m3u8_native][language=en]/wa+wv[height=1080][protocol=m3u8_native][language=en]/w[height<=1080][height>=720][language=en]/wa+wv[height<=1080][height>=720][protocol=m3u8_native][language=en]/22/b/ba+bv' $quiet --novideo "$url" >&$redirect 2>&1 ;;
    *xkcd.com*|*reddit.com*)
        $prefix qutebrowser --target window -T -R -s statusbar.show in-mode -s colors.webpage.preferred_color_scheme dark -s colors.webpage.darkmode.enabled true -s colors.webpage.darkmode.policy.images never -s tabs.show multiple -s auto_save.session false -s bindings.commands '{"normal": {"x": "quit", "xO": null, "xo": null, "q": "quit"}}' -s tabs.last_close close ":fullscreen" "$url" >&$redirect 2>&1 $suffix ;;
    *)
        readable -s ~/.config/newsboat/style.css -o /tmp/x.html "$url" >&$redirect 2>&1 && $prefix qutebrowser --target window -T -R -s statusbar.show in-mode -s colors.webpage.preferred_color_scheme dark -s tabs.show multiple -s auto_save.session false -s bindings.commands '{"normal": {"x": "quit", "xO": null, "xo": null, "q": "quit"}}' -s tabs.last_close close ":fullscreen" "/tmp/x.html" >&$redirect 2>&1 $suffix ;;
esac
