keys:
  - &host_wiggin age1nquhp6kxf5eve3x0tfmtn6lzp7mt2lqdcdacrwl4zhy2kgkc2a4qk38hvw
  - &host_delphiki age1flmap86s0cjzt0znwr08wyrfpjyvu9jrer34cqfvlrs9tcn9lupq8amlwg
  - &host_jane age1fk79eyuhtpk4xy2y5k55syu7ghcec3hh442nsdympw7sgshpeekqsntkhd
creation_rules:
  - path_regex: nixos/hosts/wiggin/.*secrets.yaml$
    key_groups:
    - age:
      - *host_wiggin
  - path_regex: nixos/hosts/wiggin/(.*/)?secrets/
    key_groups:
    - age:
      - *host_wiggin
  - path_regex: nixos/hosts/jane/.*secrets.yaml$
    key_groups:
    - age:
      - *host_wiggin
      - *host_delphiki
      - *host_jane
  - path_regex: nixos/hosts/jane/(.*/)?secrets/
    key_groups:
    - age:
      - *host_wiggin
      - *host_delphiki
      - *host_jane
  - path_regex: home-manager/j-ace-svg/.*secrets.yaml$
    key_groups:
    - age:
      - *host_wiggin
      - *host_delphiki
  - path_regex: home-manager/j-ace-svg/(.*/)?secrets/
    key_groups:
    - age:
      - *host_wiggin
      - *host_delphiki
