#!/bin/sh

# Make script fail if any individual commands fail (including in pipes)
set -e

# Early return if no changes were detected
if sudo git diff --quiet '*.nix'; then
    echo "No changes detected, exiting."
    exit 0
fi

# Autoformat your nix files
sudo alejandra . &>/dev/null \
  || ( sudo alejandra . ; echo "formatting failed!" && exit 1)

# Shows your changes
sudo git diff -U0 '*.nix'

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo sh -c 'nixos-rebuild --flake .#nixos switch &> nixos-switch.log' || (cat nixos-switch.log | grep --color error && exit 1)

# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Commit all changes witih the generation metadata
sudo git commit -am "$current"

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
