# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
# Modified (original commented out below)
{
  buildPythonPackage,
  pkgs,
  fetchurl,
}:
buildPythonPackage rec {
  pname = "pyvoicechanger";
  version = "1.5.0";
  src = fetchurl {
    url = "https://files.pythonhosted.org/packages/bb/32/a603069d3c0ac05c2dc7bf1168b9ae1b38a3905bcd683ff032bcf4ad4a2d/pyvoicechanger-1.5.0-py2.py3-none-any.whl";
    sha256 = "0hn1qaahzgb21fmi6a4ngqvfpbrv1fn3aaa26b950lsr94xbmr9v";
  };
  format = "wheel";
  doCheck = false;
  buildInputs = [];
  checkInputs = [];
  nativeBuildInputs = [];
  propagatedBuildInputs = [];
}
/*
# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}: self: super: {
  "pyvoicechanger" = super.buildPythonPackage rec {
    pname = "pyvoicechanger";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/32/a603069d3c0ac05c2dc7bf1168b9ae1b38a3905bcd683ff032bcf4ad4a2d/pyvoicechanger-1.5.0-py2.py3-none-any.whl";
      sha256 = "0hn1qaahzgb21fmi6a4ngqvfpbrv1fn3aaa26b950lsr94xbmr9v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
*/

